### PR TITLE
4 feat headermenu

### PR DESCRIPTION
**Pull request by TessDevon**
bild
bild
bild

The HTML structure for the header and menu is done. The tags have been given classes. CSS and styling are done for mobile, tablet and desktop.

### CODE REVIEW

**Comment by davidstalgren** [comment]
Looking good!! 👍

**Review by davidstalgren — APPROVED** [review]
Looking good!!! 👍

**Comment by MariaLBovin** [comment]
Looks super!

**Review by Sporesong — APPROVED** [review]
Ser jättebra ut :)

**Pull request merged**
